spring.datasource.url=jdbc:mysql://localhost:3309/despacho_db
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.port=8084


jwt.secret=bXlTdXBlclNlY3JldEtleUZvckpXVEF1dGhlbnRpY2F0aW9uMjAyNkRlc3BhY2hvQ29udGFibGU=
jwt.expiration=86400000

# Carpeta para imágenes subidas del blog
uploads.ruta=C:/despacho-uploads/
